service: go-ses

frameworkVersion: "3"

custom:
  this: ${self:service}-${self:provider.stage}

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  stage: "poc"
  region: sa-east-1
  timeout: 30
  memorySize: 128
  logRetentionInDays: 1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:VerifyEmailIdentity
          Resource: "*"

package:
  individually: true
  patterns:
    - "!./**"
    - ./bin/**

functions:
  main:
    handler: bootstrap
    package:
      artifact: bin/main.zip
    events:
      - http:
          path: /
          method: post
          cors: true
