service: alerts

custom:
  this: ${self:service}-${self:provider.stage}-handler

provider:
  name: aws
  runtime: go1.x
  stage: poc
  region: sa-east-1
  memorySize: 128
  timeout: 5
  logRetentionInDays: 1

functions:
  handler:
    name: ${self:custom.this}
    handler: bin/handler
    events:
      - http:
          path: /
          method: GET
          cors: true

resources:
  - ${file(./alerts.yml)}
