service: aws-common-reserved-concurrency-switch
frameworkVersion: "3"

custom:
  setReservedConcurrency: on # values: [on, off]
  reservedConcurrency:
    on: 2
    off: !Ref AWS::NoValue

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  memorySize: 128
  timeout: 10
  stage: poc

functions:
  handler:
    handler: index.handler
    reservedConcurrency: ${self:custom.reservedConcurrency.${self:custom.setReservedConcurrency}}
    events:
      - http:
          path: /
          method: get
          cors: true
